POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "The existing code tests need to be changed when users are added to the system",
  "important": true,
  "userId": "5f75594c9d977c2f1c179ed7"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "User id of the note creator is at the start sent along the request",
  "important": true,
  "userId": "5f75594c9d977c2f1c179ed7"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salainen"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

###


